# Generated by Django 5.0.2 on 2024-03-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_completed',
        ),
    ]
